name: Deploy Functions

on:
    push:
        branches: ["main"]
        paths:
            - functions/**
    workflow_dispatch:

permissions:
    contents: read
    id-token: write

jobs:
    build-and-deploy:
        uses: ./.github/workflows/deploy-app.yml
        with:
            package-path: "functions"
            app-name: "sanskagarwal-functions"
            deploy-type: "functionapp"
            node-version: "24.x"
        secrets: inherit
